In [7]:
# This will import code from the refactored project
import os.path
import sys
import pandas as pd

pd.set_option("display.max_columns", None)

python_dir = os.path.abspath('..')
sys.path.append(python_dir)

In [8]:
import bootcamp_2021_01

In [9]:
WORK_DIR = '../../workdir'

# Load raw data for schema discovery

## Load data

In [13]:
from pilotis_io.local.local_io_api import LocalIoApi
from pilotis_io.local import LocalPandasApi
from pilotis_io.directory_structure import dataset_raw_dir_path

In [15]:
io_api = LocalIoApi(WORK_DIR)
pandas_api = LocalPandasApi(io_api)

### Notpeter

In [16]:
dataset_version = '2015-12'

rounds_name = 'notpeter_rounds'
rounds_path = dataset_raw_dir_path(rounds_name, dataset_version)

invest_name = 'notpeter_investments'
invest_path = dataset_raw_dir_path(invest_name, dataset_version)

acq_name = 'notpeter_acquisitions'
acq_path = dataset_raw_dir_path(acq_name, dataset_version)

comp_name = 'notpeter_companies'
comp_path = dataset_raw_dir_path(comp_name, dataset_version)

rounds_files = io_api.list_files_in_dir(rounds_path)
invest_files = io_api.list_files_in_dir(invest_path)
acq_files = io_api.list_files_in_dir(acq_path)
comp_files = io_api.list_files_in_dir(comp_path)

rounds = pandas_api.load_pandas_dataset(rounds_files, encoding='unicode_escape')
invest = pandas_api.load_pandas_dataset(invest_files, encoding='unicode_escape')
acq = pandas_api.load_pandas_dataset(acq_files, encoding='unicode_escape')
companies = pandas_api.load_pandas_dataset(comp_files, encoding='unicode_escape')

### Bachelorarbeit

In [17]:
dataset_version_bachelorarbeit = '2013-12'
dataset_version_bachelorarbeit_clean = '2013-12-cleaned'

people_name = 'bachelorarbeit_people'
people_path = dataset_raw_dir_path(people_name, dataset_version_bachelorarbeit)

orga_name = 'bachelorarbeit_organizations'
orga_path = dataset_raw_dir_path(orga_name, dataset_version_bachelorarbeit_clean)

people_files = io_api.list_files_in_dir(people_path)
orga_files = io_api.list_files_in_dir(orga_path)

people = pandas_api.load_pandas_dataset(people_files)
organizations = pandas_api.load_pandas_dataset(orga_files)

### VC_Holy_Grail

In [18]:
vc_holy_grail_people_dataset_version = 'vc_holy_grail_cleaned'

vc_holy_grail_people_name = 'vc_holy_grail_people'
vc_holy_grail_people_path = dataset_raw_dir_path(vc_holy_grail_people_name, vc_holy_grail_people_dataset_version)


vc_holy_grail_people_files =  io_api.list_files_in_dir(vc_holy_grail_people_path)

vc_holy_grail_people = pandas_api.load_pandas_dataset(vc_holy_grail_people_files)

/Users/victorlandeau/Library/Caches/pypoetry/virtualenvs/bootcamp-2021-01-JvUDATpG-py3.7/lib/python3.7/site-packages/ipykernel_launcher.py:9: DtypeWarning: Columns (17,18,19,20,21) have mixed types. Specify dtype option on import or set low_memory=False.
  if __name__ == '__main__':

## Explore data

plusieurs cas : 
- VC en série A
score = 0.8 -> si tu investi sur la compagnie X, celle-ci aura 80% de chances d'être rachetée ou de partir en bourse (IPO) ou d'avoir des investissements en série B et suivantes dans les n années

- BA en seed
score = 0.8 -> si tu investi sur la compagnie X, celle-ci aura 80% de chances d'être rachetée ou de partir en bourse (IPO) ou d'avoir des investissements en série A et suivantes


dans le passé, le VC Y a investi sur X, puis X a été racheté par Z dans les n annéezs
dans le passé, le BA A a investi sur B, qui n'a jamais été racheté/eu de nouvelles levées de fonds en succès dans les n années

? mesurer la plus-value du BA/VC ?
? creuser plus tard la réalité du statut d'échec/de succès ?

In [19]:
vc_holy_grail_people.head()

,Full Name,Full Name URL,Primary Job Title,Organization Name,Primary Organization URL,Location,CB Rank,First Name,Last Name,Gender,Biography,Twitter,LinkedIn,Facebook,Number of News Articles,Number of Founded Organizations,Number of Portfolio Companies,Number of Investments,Number of Partner Investments,Number of Lead Investments,Number of Exits,Number of Events,Trend Score (7 Days),Trend Score (30 Days),Trend Score (90 Days),Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33
0,Mark Cuban,/person/mark-cuban,Owner,Dallas Mavericks,/organization/dallas-mavericks,"Dallas, Texas, United States",1,Mark,Cuban,Male,"Since the age of 12, Mark has been a natural b...",http://twitter.com/mcuban,https://www.linkedin.com/in/mark-cuban-06a0755b,http://www.facebook.com/markcuban,"2,366",4,72,96,3,8,14,11,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Barack Obama,/person/barack-obama,Founder,Obama Foundation,/organization/obama-foundation,"Washington, District of Columbia, United States",2,Barack,Obama,Male,President Barack Obama is the 44th President o...,http://twitter.com/BarackObama,http://www.linkedin.com/in/barackobama,http://www.facebook.com/barackobama,"30,897",1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,4.2,4.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Elon Musk,/person/elon-musk,"Chairman, Product Architect & CEO",Tesla,/organization/tesla-motors,"Los Angeles, California, United States",3,Elon,Musk,Male,Elon co-founded Tesla and continues to oversee...,http://twitter.com/elonmusk,https://www.linkedin.com/in/emusk,https://www.facebook.com/pages/Elon-Musk/11270...,"14,445",7,11,21,NaN,9,6,2,0.0,-0.2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Wei Guo,/person/wei-guo-2,Managing Partner,UpHonest Capital,/organization/uphonest-capital,"San Francisco, California, United States",5,Wei,Guo,Male,"Wei Guo, managing?_partner of UpHonest Capital...",NaN,https://www.linkedin.com/in/wei-guo-b9b76038/,NaN,2,2,113,119,NaN,NaN,5,1,9.1,7.6,4.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Jeff Bezos,/person/jeff-bezos,CEO,Amazon,/organization/amazon,"Seattle, Washington, United States",7,Jeff,Bezos,Male,"Jeffrey Preston Bezos, originally of Albuquerq...",https://twitter.com/jeffbezos,https://www.linkedin.com/in/jeff-bezos-76480123,NaN,"11,919",5,20,23,1,NaN,4,2,-0.9,-0.4,-0.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
companies.head()

,permalink,name,homepage_url,category_list,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,first_funding_at,last_funding_at
0,/organization/-fame,#fame,http://livfame.com,Media,10000000,operating,IND,16,Mumbai,Mumbai,1,NaN,2015-01-05,2015-01-05
1,/organization/-qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,700000,operating,USA,DE,DE - Other,Delaware City,2,2014-09-04,2014-03-01,2014-10-14
2,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,3406878,operating,NaN,NaN,NaN,NaN,1,NaN,2014-01-30,2014-01-30
3,/organization/0-6-com,0-6.com,http://www.0-6.com,Curated Web,2000000,operating,CHN,22,Beijing,Beijing,1,2007-01-01,2008-03-19,2008-03-19
4,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,-,operating,USA,IL,"Springfield, Illinois",Champaign,1,2010-01-01,2014-07-24,2014-07-24

In [21]:
companies.status.value_counts()

operating    53034
closed        6238
acquired      5549
ipo           1547
Name: status, dtype: int64

In [22]:
people.head()

,crunchbase_uuid,type,first_name,last_name,crunchbase_url,profile_image_url,facebook_url,twitter_url,linkedin_url,location_city,location_region,location_country_code,title,organization,organization_crunchbase_url
0,ed13cd36-fe2b-3707-197b-0c2d56e37a71,Person,Ben,Elowitz,https://www.crunchbase.com/person/ben-elowitz?...,https://crunchbase-production-res.cloudinary.c...,http://www.facebook.com/elowitz,http://twitter.com/elowitz,http://www.linkedin.com/in/benelowitz,Seattle,Washington,US,Managing Director at Madrona Venture Group,Madrona Venture Group,https://www.crunchbase.com/organization/madron...
1,5ceca97b-493c-1446-6249-5aaa33464763,Person,Kevin,Flaherty,https://www.crunchbase.com/person/kevin-flaher...,https://crunchbase-production-res.cloudinary.c...,NaN,https://twitter.com/tallkp,http://www.linkedin.com/in/kevinflaherty,NaN,NaN,NaN,Team Member at DRSmedia,DRSmedia,https://www.crunchbase.com/organization/drs650...
2,9f99a98a-aa97-b30b-0d36-db67c1d277e0,Person,Raju,Vegesna,https://www.crunchbase.com/person/raju-vegesna...,https://crunchbase-production-res.cloudinary.c...,NaN,NaN,https://www.linkedin.com/pub/raju-vegesna/1/65...,San Francisco,California,US,Chief Evangelist at Zoho,Zoho,https://www.crunchbase.com/organization/zoho
3,6e1bca72-a865-b518-b305-31214ce2d1b0,Person,Ian,Wenig,https://www.crunchbase.com/person/ian-wenig?ut...,https://crunchbase-production-res.cloudinary.c...,NaN,NaN,http://www.linkedin.com/profile/view?id=1633445,NaN,NaN,NaN,VP Business Development at Zoho,Zoho,https://www.crunchbase.com/organization/zoho
4,80d25c23-9726-9dda-5852-39cdf4810ea5,Person,Ron,Gorodetzky,https://www.crunchbase.com/person/ron-gorodetz...,https://crunchbase-production-res.cloudinary.c...,NaN,NaN,https://twitter.com/ronwinbeta,NaN,NaN,NaN,Co-Founder and CTO at fflick,fflick,https://www.crunchbase.com/organization/fflick

In [23]:
acq.head()

,company_permalink,company_name,company_category_list,company_country_code,company_state_code,company_region,company_city,acquirer_permalink,acquirer_name,acquirer_category_list,acquirer_country_code,acquirer_state_code,acquirer_region,acquirer_city,acquired_at,acquired_month,price_amount,price_currency_code
0,/organization/003-ru,003.RU,Consumer Electronics|Electronics|Internet,RUS,48,Moscow,Moscow,/organization/media-saturn,Media Saturn,Enterprise Software|Media|Sales and Marketing,ESP,56,Barcelona,Barcelona,2012-07-23,2012-07,NaN,USD
1,/organization/0958572-b-c-ltd,0958572 B.C. Ltd.,NaN,NaN,NaN,NaN,NaN,/organization/atlas-intellectual-property-mana...,ATLAS Intellectual Property Management Co.,Finance|FinTech|Mobile|Telecommunications,USA,WA,Seattle,Seattle,2012-02-02,2012-02,9000000.0,USD
2,/organization/1-800-communications,1-800 Communications,NaN,USA,NY,Long Island,Hicksville,/organization/carsdirect-com,CarsDirect.com,E-Commerce,USA,CA,Los Angeles,El Segundo,2005-06-12,2005-06,NaN,USD
3,/organization/1-800-contacts,1-800 Contacts,Consumer Goods|Retail,USA,UT,Salt Lake City,Draper,/organization/thomas-h-lee-partners,Thomas H. Lee Partners,Business Development|Impact Investing|Investme...,USA,MA,Boston,Boston,2014-01-07,2014-01,NaN,USD
4,/organization/1-844-446-4460-pogo-customer-ser...,Games Support +1-800-311-5934 Pogo Games techn...,NaN,NaN,NaN,NaN,NaN,/organization/pogo-customer-service-number-1-8...,Games Support +1-800-311-5934 Pogo Games techn...,NaN,USA,NY,New York City,Mamaroneck,2001-02-02,2001-02,NaN,USD

In [24]:
invest.head()

,company_permalink,company_name,company_category_list,company_country_code,company_state_code,company_region,company_city,investor_permalink,investor_name,investor_country_code,investor_state_code,investor_region,investor_city,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/0-6-com,0-6.com,Curated Web,CHN,22,Beijing,Beijing,/organization/dt-capital-partners,DT Capital Partners,CHN,23,Shanghai,Shanghai,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,2008-03-19,2000000.0
1,/organization/004-technologies,004 Technologies,Software,USA,IL,"Springfield, Illinois",Champaign,/organization/venturecapital-de,VCDE Venture Partners,DEU,5,Frankfurt,Frankfurt,/funding-round/1278dd4e6a37fa4b7d7e06c21b3c1830,venture,NaN,2014-07-24,NaN
2,/organization/01games-technology,01Games Technology,Games,HKG,NaN,Hong Kong,Hong Kong,/organization/cyberport-hong-kong,Cyberport Hong Kong,HKG,NaN,Hong Kong,Hong Kong,/funding-round/7d53696f2b4f607a2f2a8cbb83d01839,undisclosed,NaN,2014-07-01,41250.0
3,/organization/0xdata,H2O.ai,Analytics,USA,CA,SF Bay Area,Mountain View,/organization/capital-one,Capital One,USA,VA,"Washington, D.C.",Mclean,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,B,2015-11-09,20000000.0
4,/organization/0xdata,H2O.ai,Analytics,USA,CA,SF Bay Area,Mountain View,/organization/nexus-venture-partners,Nexus Venture Partners,USA,CA,SF Bay Area,Menlo Park,/funding-round/383a9bd2c04f7038bb543ccef5ba3eae,seed,NaN,2013-05-22,3000000.0

In [25]:
rounds.head()

,company_permalink,company_name,company_category_list,company_country_code,company_state_code,company_region,company_city,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,#fame,Media,IND,16,Mumbai,Mumbai,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,2015-01-05,10000000.0
1,/organization/-qounter,:Qounter,Application Platforms|Real Time|Social Network...,USA,DE,DE - Other,Delaware City,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,2014-10-14,NaN
2,/organization/-qounter,:Qounter,Application Platforms|Real Time|Social Network...,USA,DE,DE - Other,Delaware City,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,2014-03-01,700000.0
3,/organization/-the-one-of-them-inc-,"(THE) ONE of THEM,Inc.",Apps|Games|Mobile,NaN,NaN,NaN,NaN,/funding-round/650b8f704416801069bb178a1418776b,venture,B,2014-01-30,3406878.0
4,/organization/0-6-com,0-6.com,Curated Web,CHN,22,Beijing,Beijing,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,2008-03-19,2000000.0

### Seed vs angel

In [26]:
angel_companies = rounds[rounds.funding_round_type == "angel"].company_name	
seeds_and_angels = rounds[(rounds.funding_round_type == "seed") & 
                         (rounds.company_name.isin(angel_companies))]
seeds_and_angels.head(10)

,company_permalink,company_name,company_category_list,company_country_code,company_state_code,company_region,company_city,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
92,/organization/121nexus,121nexus,Health Diagnostics|Medical Devices|Personaliza...,USA,RI,Providence,Providence,/funding-round/964bf36d0f84b63c073afb4ef68380d6,seed,NaN,2012-02-06,14000.0
94,/organization/121nexus,121nexus,Health Diagnostics|Medical Devices|Personaliza...,USA,RI,Providence,Providence,/funding-round/fac223682361b8f57d004009f31191fc,seed,NaN,2012-04-20,55000.0
124,/organization/15five,15Five,Software,USA,CA,SF Bay Area,San Francisco,/funding-round/510827fe635f2c65dffb69884763dfc6,seed,NaN,2014-10-02,2200000.0
179,/organization/1mpact-revolution-powering-helpf...,1mpact Revolution - Powering Helpfreely.org,Non Profit|Online Shopping|Social Fundraising,ESP,53,Las Palmas De Gran Canaria,Las Palmas De Gran Canaria,/funding-round/9cfa0c6227634fbac4b4705349f5e85f,seed,NaN,2013-09-10,92582.0
283,/organization/250ok,250ok,Software,USA,IN,Indianapolis,Indianapolis,/funding-round/7633ab9e95c3783c2836af173614ff0a,seed,NaN,2012-09-01,200000.0
289,/organization/280-north,280 North,Presentations|Software,USA,CA,SF Bay Area,San Francisco,/funding-round/4433764c0e634139c2d831a2ba13a158,seed,NaN,2008-01-01,NaN
337,/organization/2threads,2threads,Art|Beauty|Fashion|Lifestyle|Music|Social Medi...,AUS,2,Sydney,Sydney,/funding-round/6da1098e8c5703abb6d909b0458e20da,seed,NaN,2007-08-01,100000.0
415,/organization/3baysover,3BaysOver,Networking|Online Travel|Travel,CHE,7,Geneva,Geneva,/funding-round/8321dcb6834cf9ee6aaac4834907d015,seed,NaN,2011-08-01,375000.0
421,/organization/3clickemr-corporation,3ClickEMR Corporation,Consumer Electronics|Electronic Health Records...,USA,MA,Boston,West Roxbury,/funding-round/34dc67067884dfc0623f0e6d7b61ea03,seed,NaN,2010-06-23,250000.0
445,/organization/3d-industri-es,3D Industri.es,3D|Curated Web|Manufacturing|Search|Supply Cha...,GBR,H9,London,London,/funding-round/12b97a44d964d8f541e034208e34633e,seed,NaN,2012-03-01,350000.0

In [27]:
rounds[rounds.company_name == "3D Industri.es"].sort_values("funded_at")

,company_permalink,company_name,company_category_list,company_country_code,company_state_code,company_region,company_city,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
445,/organization/3d-industri-es,3D Industri.es,3D|Curated Web|Manufacturing|Search|Supply Cha...,GBR,H9,London,London,/funding-round/12b97a44d964d8f541e034208e34633e,seed,NaN,2012-03-01,350000.0
446,/organization/3d-industri-es,3D Industri.es,3D|Curated Web|Manufacturing|Search|Supply Cha...,GBR,H9,London,London,/funding-round/d79bd2f237f9e56334e7d8e77bf5e1f6,angel,NaN,2013-03-01,850000.0

### Rounds vs invest

In [28]:
rounds.shape, invest.shape

((114949, 12), (168647, 18))

In [29]:
all_unique_rounds = rounds[['company_name', 'funded_at']].drop_duplicates()

In [30]:
all_unique_invest = invest[['company_name', 'funded_at']].drop_duplicates()

In [31]:
invest_and_rounds_joined = all_unique_invest\
                            .set_index(['company_name', 'funded_at'])\
                            .assign(invest=1)\
                            .join(
                                all_unique_rounds\
                                    .set_index(['company_name', 'funded_at'])\
                                    .assign(rounds=1), how='outer')
invest_and_rounds_joined

                                  invest  rounds
company_name          funded_at
#BratPackStyle, LLC.  2015-06-01     1.0     1.0
'Rock' Your Paper     2012-08-09     1.0     1.0
                      2013-12-01     1.0     1.0
( caravelo (          2012-01-01     1.0     1.0
.                     2015-01-15     1.0     NaN
...                                  ...     ...
ZYOMYX                2010-01-29     NaN     1.0
Zyraz Technology      2013-02-15     NaN     1.0
Zyrra                 2012-10-18     NaN     1.0
                      2010-12-15     NaN     1.0
Zzzzapp Wireless ltd. 2011-11-01     NaN     1.0

[114007 rows x 2 columns]

In [32]:
invest_and_rounds_joined.sum()

invest     71250.0
rounds    114006.0
dtype: float64

In [33]:
rounds.funding_round_type.value_counts()

venture                  55494
seed                     30524
debt_financing            6895
angel                     6094
undisclosed               4897
equity_crowdfunding       3257
private_equity            2285
grant                     2200
convertible_note          1817
post_ipo_equity            638
product_crowdfunding       410
non_equity_assistance      191
post_ipo_debt              152
secondary_market            95
Name: funding_round_type, dtype: int64

In [34]:
invest.funding_round_type.value_counts()

venture                  104157
seed                      43747
angel                      6493
undisclosed                5608
private_equity             2779
debt_financing             2197
convertible_note           1590
grant                      1220
equity_crowdfunding         325
post_ipo_equity             204
non_equity_assistance       132
secondary_market            109
post_ipo_debt                54
product_crowdfunding         32
Name: funding_round_type, dtype: int64

In [35]:
invest.funding_round_code.value_counts()

A    31436
B    23395
C    14796
D     7263
E     2851
F     1041
G      235
H       45
Name: funding_round_code, dtype: int64

### Failures and successes

In [36]:
seriesA = invest[invest.funding_round_code == "A"][["company_name", "funded_at"]]
seriesB = invest[invest.funding_round_code == "B"][["company_name"]].drop_duplicates()
seriesC = invest[invest.funding_round_code == "C"][["company_name"]].drop_duplicates()
acq_companies = acq[["company_name"]].assign(acq=1).drop_duplicates()
companies_with_people_info = people[["organization"]].drop_duplicates()
orga_info = organizations[["name"]].drop_duplicates()
companies_state = companies[["name", "status"]].drop_duplicates()

In [37]:
series_a_follow_up = seriesA.set_index("company_name").assign(seriesA=1).join(
    seriesB.set_index("company_name").assign(seriesB=1),
    how="left").join(
    seriesC.set_index("company_name").assign(seriesC=1),
    how="left").join(
    acq_companies.set_index("company_name"),
    how="left").join(
    companies_with_people_info.assign(known_people=1).set_index("organization"),
    how="left").join(
    orga_info.assign(known_orga_suppl_infos=1).set_index("name"),
    how="left").join(
    companies.set_index("name"),
    how="left")
series_a_follow_up.sum()

funded_at                 2012-01-012008-03-192013-11-072013-11-072013-1...
seriesA                                                               31845
seriesB                                                               11317
seriesC                                                                4761
acq                                                                    5383
known_people                                                          23898
known_orga_suppl_infos                                                28055
permalink                 /organization/caravelo/organization/0-6-com/or...
funding_total_usd         1089811200000021400000214000002140000021400000...
status                    operatingoperatingipoipoipoipoipoipoacquiredac...
funding_rounds                                                        93785
last_funding_at           2015-07-222008-03-192015-02-202015-02-202015-0...
dtype: object

In [38]:
failures_new_invests = series_a_follow_up[(series_a_follow_up.seriesB.isnull()) &
                                      (series_a_follow_up.acq.isnull()) &
                                      (series_a_follow_up.status == "operating") &
                                      (series_a_follow_up.funded_at < "2013-12")]
failures_closure = series_a_follow_up[(series_a_follow_up.status == "closed")]

successes = series_a_follow_up[((series_a_follow_up.seriesB.notnull()) |
                            (series_a_follow_up.acq.notnull()) | 
                              (series_a_follow_up.status == "ipo") |
                              (series_a_follow_up.status == "acquired")) &
                              (series_a_follow_up.status != "closed")]
print(f"""
On a en tout {len(failures_new_invests) + len(failures_closure) + len(successes)} startups qui
pourront appartenir à notre échantillon d'apprentissage.
Parmis elles, a {len(failures_new_invests) + len(failures_closure)} échecs, dont {len(failures_new_invests)} 
startups sans nouvel investissements dans les 2 dernières années et {len(failures_closure)} 
startups qui ont fermé.
On a par ailleurs {len(successes)} companies pour lesquels l'investissement a été en succès 
(nouvel investissement, aquisition, IPO)
""")

On a en tout 23493 startups qui
pourront appartenir à notre échantillon d'apprentissage.
Parmis elles, a 9368 échecs, dont 7291
startups sans nouvel investissements dans les 2 dernières années et 2077
startups qui ont fermé.
On a par ailleurs 14125 companies pour lesquels l'investissement a été en succès
(nouvel investissement, aquisition, IPO)

In [39]:
failures.known_people.sum() / len(failures), successes.known_people.sum() / len(successes)

NameError: name 'failures' is not defined

In [ ]:
failures.known_orga_suppl_infos.sum() / len(failures), successes.known_orga_suppl_infos.sum() / len(successes)

Infos de features sans enrichissements externes :
 - info sur les personnes travaillant dans la startup (~75% des cas : colonnes facebook_url	twitter_url	linkedin_url dans dataset people, nombre)
 - infos sur la présence de la startup sur les réseaux sociaux (~90% des cas : twitter_url, facebook_url, linkedin_url dans organizations)
 - secteur d'activité (category_list dans companies, ? dans organizations)
 - date de crétion
 - zone géographique
 - stats sur le VC qui cherche à investir dans la startup
 - investissements et investisseurs antérieurs dans la startup

## Join tests

In [ ]:
company_names_in_holy = vc_holy_grail_people[['Organization Name']].drop_duplicates().set_index("Organization Name")
print(company_names_in_holy.shape)

company_names_in_invest = invest[['company_name']].drop_duplicates().set_index("company_name")
print(company_names_in_invest.shape)

company_names_in_invest.join(company_names_in_holy, how="inner").shape

In [ ]:
vc_holy_grail_people